const mongoose = require('mongoose');

const EncounterSchema = new mongoose.Schema({
  encounter_id: String,
  video_id: String,
  video_type: String,
  appointment_id: String,
  create_date: String,
  appointment_date: String,
  start_date: String,
  encounter_duration: String,
  reason_for_visit: String,
  client_name: String,
  group_name: String,
  carepoint: String,
  type: String,
  philhealth_tranche: String,
  philhealth_transaction_no: String,
  philhealth_transmittal_id: String,
  philhealth_case_no: String,
  philhealth_member_pin: String,
  philhealth_member_type: String,
  barangay: String,
  cancelled: String,
  patient_mrn: String,
  patient_name: String,
  patient_age: String,
  patient_gender: String,
  patient_in: String,
  patient_out: String,
  patient_duration: String,
  clinician_id: String,
  clinician_name: String,
  clinician_in: String,
  clinician_out: String,
  clinician_duration: String,
  state: String,
  presenter_names: String,
  cpt_codes: String,
  medications: String,
  lab_orders_total: String,
  imaging_orders_total: String,
  other_orders_total: String,
  forms: String,
  icd_codes: String,
  encounter_signed: String,
  status: String,
  cc_rcvd: String,
  cash_rcvd: String,
  reason_for_cancel: String
});

module.exports = mongoose.model('Encounter', EncounterSchema);
